### ISSUE TITLE
[FEATURE] Schematic Pin List

### ISSUE THREAD

**Issue by s-y-wu** [unihd-cag/skillbridge#243]
## Problem
When exporting pin lists from schematics, I want to use skillbridge to set properties within `pinList->prop`. In SKILL, it looks like this:
```lisp
pinList = schSchemToPinList(lib cell "schematic")  ; pinList->prop is nil as reported in CIW...
pinList->prop->schCvCreationMethod = "Replace"     ; yet this is somehow valid (seems like magic to me)
schPinListToView(lib cell "symbol" pinList 'schPinListToSymbolGen)
```
Specifically, line 2 accesses properties of `pinList->prop` despite it being `nil`. If written using skillbridge, Python errors out
```python
from skillbridge import Workspace

ws = Workspace.open()
lib = "foo"
cell = "bar"
pin_list = ws.sch.schem_to_pin_list(lib, cell, "schematic")

print(pin_list["prop"])
# [None]

setattr(pin_list["prop"], "schCvCreationMethod", "Replace")
# AttributeError: 'list' object has no attribute 'schCvCreationMethod'

ws.sch.pin_list_to_view(lib, cell, "symbol", pin_list, "schPinListToSymbolGen")
```

##  Potential Solution
- Add an encoder for`ws.sch.*_to_pin_list` methods. Have them return a special PinList object instead of a `dict` with two attributes: `prop` and `pins`. 
- Set the list currently stored in `pin_list["pins"]` as `pin_list.pins`
- Set`pin_list.prop` stores another class like PinListProperties that intializes `pin_list.prop.schCvCreationMethod = None` 
- Translate any assignment of `pin_list.prop.schCvCreationMethod = "Replace"` into `pinList->prop->schCvCreationMethod = "Replace"`
- Add a decoder for every `ws.sch.pin_list_to_*` to set pin_list.prop back to the current dictionary with `pin_list["prop"] = [None]` before sending it through the current process.

## Additional Context & Bug Report
In my design automation Python scripts, I need to:
1.   Export a schematic cell view to create a symbol cell view
2.  Run this without clicking warning popup windows.

The skill API offers a few ways to accomplish task [1]. My first attempt was:
```python
pin_list = ws.sch.schem_to_pin_list(lib, cell, "schematic")
ws.sch.pin_list_to_symbol(lib, cell, "symbol", pin_list)
```
This worked fine for 7 of my schematics (basic pins, nets, and symbol instances). But once I got to my 8th and largest schematic (many symbol instances), **virtuoso crashed every time**. However, I knew this was a skillbridge specific issues because manually inputting the following code in CIW successfully generated the 8th schematic's symbol **without crashing virtuoso, consistently**.
```
pinList = schSchemToPinList(lib cell "schematic")
schPinListToView(lib cell "symbol" pinList 'schPinListToSymbolGen)
```
I suspected the python `pin_list` was responsible. And indeed, this workaround never crashes virtuoso:
```python
ws.sch.view_to_view(lib, cell, lib, cell, "schematic", "symbol", "schSchematicToPinList", "schPinListToSymbol")
```
However, all of these methods described above do not accomplish task [2], as a popup dialog appears to settle the ambiguity of the pin list property's schCvCreationMethod, which could either be "Modify" or "Replace". The only workaround that accomplished both [1] and [2] was manual function loading with Skill code:
```python
skill_code = """
procedure(mySymbolSave(lib cell)
    let( (pin_list)
        pin_list = schSchemToPinList(lib cell "schematic")
        pin_list->prop->schCvCreationMethod = "Replace"
        schPinListToView(lib cell "symbol" pin_list 'schPinListToSymbolGen)
    ) ; let
) ; procedure
"""
with tempfile.NamedTemporaryFile(mode='w+', suffix=".il") as temp_file:
    temp_file.write(skill_code)
    temp_file.seek(0)
    # seek breaks the race condition and allows loaders to read from the beginning
    ws['load'](temp_file.name)
ws['mySymbolSave'](lib, cell)
```
This works, but having more direct solution in python would be great!

**Comment by TM90** [comment]
> ## Problem
> 
> When exporting pin lists from schematics, I want to use skillbridge to set properties within `pinList->prop`. In SKILL, it looks like this:
> 
> ```lisp
> pinList = schSchemToPinList(lib cell "schematic")  ; pinList->prop is nil as reported in CIW...
> pinList->prop->schCvCreationMethod = "Replace"     ; yet this is somehow valid (seems like magic to me)
> schPinListToView(lib cell "symbol" pinList 'schPinListToSymbolGen)
> ```
> 
> Specifically, line 2 accesses properties of `pinList->prop` despite it being `nil`. If written using skillbridge, Python errors out
> 
> ```python
> from skillbridge import Workspace
> 
> ws = Workspace.open()
> lib = "foo"
> cell = "bar"
> pin_list = ws.sch.schem_to_pin_list(lib, cell, "schematic")
> 
> print(pin_list["prop"])
> # [None]
> 
> setattr(pin_list["prop"], "schCvCreationMethod", "Replace")
> # AttributeError: 'list' object has no attribute 'schCvCreationMethod'
> 
> ws.sch.pin_list_to_view(lib, cell, "symbol", pin_list, "schPinListToSymbolGen")
> ```

The Problem here is that the types between Python and Skill are not completely equivalent. And sometimes the type translation can be  ambiguous. In this on skill side we have a disembodied property list which on python side is translated as a dictionary. The empty disembodied property list `(nil)` is ambiguous in this case and could be either `[None]`, `[False]`, `[[]]` or `{}` on the python side and all are valid in different circumstances.

To still fill the property you can assign a dictionary which will be translated correclty to a disembodied property list.

``` python
from skillbridge import Workspace
 
ws = Workspace.open()
lib = "foo"
cell = "bar"
pin_list = ws.sch.schem_to_pin_list(lib, cell, "schematic")

pin_list["prop"] =  {"schCvCreationMethod": "Replace"}
ws.sch.pin_list_to_view(lib, cell, "symbol", pin_list, "schPinListToSymbolGen")
```

Please let us know whether this solutions works and resolves your problem

**Comment by s-y-wu** [comment]
Yes, I tried your suggestion. It looks like skillbridge could digest the new values in `pin_list["prop"]`, and my first 7 schematics were saving as symbols properly without popup windows, as desired.

In this case, I'd be happy to mark the feature request as resolved. Everything looks good, except for this one little thorn.

The 8th schematic is still crashing virtuoso. Again, running the SKILL code manually in the CIW to save the 8th schematic as a symbol does NOT crash virtuoso, so this is distinctly an issue when skillbridge is involved. However, this issue maybe difficult to replicate and debug.

My Python traceback:
```
  File "/path/to/utils.py, line 239, in save_schematic_as_symbol
    ws.sch.pin_list_to_view(library, cell, "symbol", pin_list, "schPinListToSymbolGen")
  File "/path/to/venv/lib/python3.12/site-packages/skillbridge/client/functions.py", line 42, in __call__
    result = self._channel.send(command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.12/site-packages/skillbridge/client/channel.py", line 158, in send
    return self._receive_only()
           ^^^^^^^^^^^^^^^^^^^^
  File "/path/to/ver02/venv/lib/python3.12/site-packages/skillbridge/client/channel.py", line 154, in _receive_only
    return self.decode_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/radio/python_env/ver02/venv/lib/python3.12/site-packages/skillbridge/client/channel.py", line 40, in decode_response
    status, response = response.split(' ', maxsplit=1)
    ^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

Here's an excerpt from virtuoso's crash report. Looks like there is a segmentation fault:
```
startdate:Mon Jan 8 15:58:02 2024
crashdate:Wed Jan 10 09:20:23 2024
appname:virtuoso
version:@(#)$CDS: virtuoso version IC23.1-64b 10/31/2023 23:29 (cpgbld22) $
subversion:IC23.1-64b.ISR3.27
mem:1931337728 (total 1621516455936memavail:957566592k (total 1976728152k)
signal:SegFault(11)
pstack:Thread 5 (Thread 0x2ae3d9c6e700 (LWP 199732)):
pstack:#0  0x00002ae3bc8b720d in poll () from libc.so.6
pstack:#1  0x00002ae3b3550022 in _xcb_conn_wait () from libxcb.so.1
pstack:#2  0x00002ae3b3551c6f in xcb_wait_for_event () from libxcb.so.1
pstack:#3  0x00002ae3d3ab23e0 in ?? () from libcdsQt5XcbQpa.so.5
pstack:#4  0x00002ae3b0959f6f in ?? () from libcdsQt5Core.so.5
pstack:#5  0x00002ae3a82d1dd5 in start_thread () from libpthread.so.0
pstack:#6  0x00002ae3bc8c1ead in clone () from libc.so.6
pstack:Thread 4 (Thread 0x2ae3da1c1700 (LWP 199752)):
pstack:#0  0x00002ae3bc8b72cf in ppoll () from libc.so.6
pstack:#1  0x00002ae3b0b978a9 in qt_safe_poll(pollfd*, unsigned long, timespec const*) () from libcdsQt5Core.so.5
pstack:#2  0x00002ae3b0b98d33 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from libcdsQt5Core.so.5
pstack:#3  0x00002ae3b0b43f5b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from libcdsQt5Core.so.5
pstack:#4  0x00002ae3b0958f1e in QThread::exec() () from libcdsQt5Core.so.5
pstack:#5  0x00002ae3d3bc82c7 in ?? () from libcdsQt5DBus.so.5
pstack:#6  0x00002ae3b0959f6f in ?? () from libcdsQt5Core.so.5
pstack:#7  0x00002ae3a82d1dd5 in start_thread () from libpthread.so.0
pstack:#8  0x00002ae3bc8c1ead in clone () from libc.so.6
pstack:Thread 3 (Thread 0x2ae3e757a700 (LWP 205294)):
pstack:#0  0x00002ae3bc8b8f73 in select () from libc.so.6
pstack:#1  0x000000000c12c7f7 in NotifierThreadProc ()
pstack:#2  0x00002ae3a82d1dd5 in start_thread () from libpthread.so.0
pstack:#3  0x00002ae3bc8c1ead in clone () from libc.so.6
pstack:Thread 2 (Thread 0x2ae3ea175700 (LWP 213898)):
pstack:#0  0x00002ae3a82d8e3d in nanosleep () from libpthread.so.0
pstack:#1  0x0000000019a36956 in eli::eliRecheckControl::recheckWorker() ()
pstack:#2  0x00002ae3bc30de43 in ?? () from libstdc++.so.6
pstack:#3  0x00002ae3a82d1dd5 in start_thread () from libpthread.so.0
pstack:#4  0x00002ae3bc8c1ead in clone () from libc.so.6
pstack:Thread 1 (Thread 0x2ae3d2aa4640 (LWP 199667)):
pstack:#0  0x00002ae3a82d9179 in waitpid () from libpthread.so.0
pstack:#1  0x00002ae3af65eb30 in voSystem () from libvirtuos_sh.so
pstack:#2  0x00002ae3af653e5a in mopProcessCdsLog () from libvirtuos_sh.so
pstack:#3  0x00002ae3af64bf17 in voDoAbortFuncs () from libvirtuos_sh.so
pstack:#4  0x00002ae3af64c0c9 in voSigAbortInfo () from libvirtuos_sh.so
pstack:#5  <signal handler called>
pstack:#6  0x00002ae3b1260aaf in ilSet1 () from libil_sh.so
pstack:#7  0x00002ae3b128e8c8 in iliVcodeEval2C () from libil_sh.so
pstack:#8  0x00002ae3b128b4f5 in iliVcodeEval2 () from libil_sh.so
pstack:#9  0x00002ae3b128b601 in ilxSkillEval2 () from libil_sh.so
pstack:#10 0x00002ae3b1299852 in _ilErrSet () from libil_sh.so
pstack:#11 0x00000000190a7bba in dbCellViewCallback::onBeginPurge(OpenAccess_4::oaDesign*, unsigned int) ()
pstack:#12 0x00002ae3afb909cb in OpenAccess_4::oaVersionedObserver<OpenAccess_4::oaDesign, 1u>::notifyBeginPurgeObservers(OpenAccess_4::oaDesign*, unsigned int) () from liboaDesign.so
pstack:#13 0x00002ae3afb76a4e in OpenAccess_4::oaDesignData::prePurge() () from liboaDesign.so
pstack:#14 0x00002ae3b06152f2 in OpenAccess_4::oaDatabase::purge() () from liboaBase.so
pstack:#15 0x00002ae3afb61547 in OpenAccess_4::oaDesign::purge() () from liboaDesign.so
pstack:#16 0x0000000018fe1445 in dbClose ()
pstack:#17 0x00000000190f63d8 in dbfClose ()
pstack:#18 0x00002ae3b128f969 in iliVcodeEval2C () from libil_sh.so
pstack:#19 0x00002ae3b128b4f5 in iliVcodeEval2 () from libil_sh.so
pstack:#20 0x00002ae3b128b601 in ilxSkillEval2 () from libil_sh.so
pstack:#21 0x00002ae3b1288e27 in iliEvalString () from libil_sh.so
pstack:#22 0x00002ae3b128e44c in iliVcodeEval2C () from libil_sh.so
pstack:#23 0x00002ae3b128b4f5 in iliVcodeEval2 () from libil_sh.so
pstack:#24 0x00002ae3b128b601 in ilxSkillEval2 () from libil_sh.so
pstack:#25 0x00002ae3b1288e27 in iliEvalString () from libil_sh.so
pstack:#26 0x00002ae3b128e44c in iliVcodeEval2C () from libil_sh.so
pstack:#27 0x00002ae3b128b4f5 in iliVcodeEval2 () from libil_sh.so
pstack:#28 0x00002ae3b1297182 in ilApply () from libil_sh.so
pstack:#29 0x00002ae3b1299862 in _ilErrSet () from libil_sh.so
pstack:#30 0x00002ae3b1289ea8 in iliCallSyntaxHelper () from libil_sh.so
pstack:#31 0x00002ae3b128da89 in iliVcodeEval2C () from libil_sh.so
pstack:#32 0x00002ae3b128b4f5 in iliVcodeEval2 () from libil_sh.so
pstack:#33 0x00002ae3b1297182 in ilApply () from libil_sh.so
pstack:#34 0x00002ae3b1262252 in ilxUnwindProtect () from libil_sh.so
pstack:#35 0x00002ae3b128fae7 in iliVcodeEval2C () from libil_sh.so
pstack:#36 0x00002ae3b128b4f5 in iliVcodeEval2 () from libil_sh.so
pstack:#37 0x00002ae3b1297182 in ilApply () from libil_sh.so
pstack:#38 0x00002ae3b1299b76 in ilErrSetApply () from libil_sh.so
pstack:#39 0x00002ae3acd0525e in _ipcComCall(iltLispval*, ipctChild*, iltLispval*) () from libcdsIlIpc_sh.so
pstack:#40 0x00002ae3acd05397 in _ipcBufferMessageForClient(ipctChild*, char const*, unsigned int, unsigned int) () from libcdsIlIpc_sh.so
pstack:#41 0x00002ae3acd05ff8 in _ipcDispatch(ipctChild*) () from libcdsIlIpc_sh.so
pstack:#42 0x00002ae3acd065fa in _ipcComDispatch(void*, int*, void**) () from libcdsIlIpc_sh.so
pstack:#43 0x000000001cc200a6 in non-virtual thunk to HiemQtNotifier::dispatch() ()
pstack:#44 0x000000001cc2059d in HiemQtDispatchQueue::dispatchNextInQueue() ()
pstack:#45 0x00002ae3b0b79b45 in ?? () from libcdsQt5Core.so.5
pstack:#46 0x00002ae3b0b7d884 in QSocketNotifier::activated(int, QSocketNotifier::QPrivateSignal) () from libcdsQt5Core.so.5
pstack:#47 0x00002ae3b0b7df25 in QSocketNotifier::event(QEvent*) () from libcdsQt5Core.so.5
pstack:#48 0x00002ae3b21b3bef in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from libcdsQt5Widgets.so.5
pstack:#49 0x00002ae3b21bc3c8 in QApplication::notify(QObject*, QEvent*) () from libcdsQt5Widgets.so.5
pstack:#50 0x00002ae3b0b451fa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from libcdsQt5Core.so.5
pstack:#51 0x00002ae3b0b989cb in QEventDispatcherUNIXPrivate::activateSocketNotifiers() () from libcdsQt5Core.so.5
pstack:#52 0x00002ae3b0b98dfb in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from libcdsQt5Core.so.5
pstack:#53 0x00002ae3d3ab346e in ?? () from libcdsQt5XcbQpa.so.5
pstack:#54 0x000000001ca5c823 in hiiFillCIWInPortCB ()
pstack:#55 0x00002ae3b12bd204 in iliBGetc () from libil_sh.so
pstack:#56 0x00002ae3b12bec4a in ilGetCharPort () from libil_sh.so
pstack:#57 0x00002ae3b12353d4 in ilFillBuffer(char*, unsigned long*, int, void*) () from libil_sh.so
pstack:#58 0x00002ae3b123a050 in ilyylex(ILYYSTYPE*, ILYYLTYPE*, void*) () from libil_sh.so
pstack:#59 0x00002ae3b122d1c4 in ilyyparse(void*, iltLocalParserData*) () from libil_sh.so
pstack:#60 0x00002ae3b127bf00 in ilParserReent () from libil_sh.so
pstack:#61 0x00002ae3b128730c in ilReadport () from libil_sh.so
pstack:#62 0x00002ae3b1299ec9 in iliTopLevel () from libil_sh.so
pstack:#63 0x000000001ca727ef in hiMainLoop ()
pstack:#64 0x000000000be322de in rde::startHiMainLoop() ()
pstack:#65 0x000000000c0e87c4 in Tcl_MainEx ()
pstack:#66 0x0000000016c6f261 in TclCommandAdaptor::mainLoop(int, char**, char const*, std::vector<ctuString, std::allocator<ctuString> > const&, void (*)()) ()
pstack:#67 0x00000000135d4259 in finaleEntry(int, char**, char const*, bool, finaleAppHarness*) ()
pstack:#68 0x000000000bcf4eab in rdeStartMain(int, char**) ()
pstack:#69 0x0000000006d9f3ed in main ()
```

If it's possible to glean any information from the crash report, we can try to investigate further. But if it seems like a dead end, I'll just rely on my workaround and we can close the ticket.

**Comment by nielsbuwen** [comment]
So it seems like the large pin list is crashing something. We can avoid sending that by using global variables:

```python
g = ws.globals('my_globals')

# notice the `>>` and the `var`
g.pin_list << ws.sch.schem_to_pin_list.var(lib, cell, "schematic")  # pinList = wsSchSchemToPinList(...)
g.properties << ws['get'].var(g.pin_list, 'prop')  # properties = pinList->prop
ws['putprop'](g.properties, 'Replace', 'schCvCreationMethod')  # prop->schCvCreationMethod = "Replace"
ws.sch.pin_list_to_view(lib, cell, "symbol", g.pin_list, Symbol('schPinListToSymbolGen'))
```

**Comment by s-y-wu** [comment]
Yes, this solution saves my 8th schematic without crashing Virtuoso! The Globals concept is a neat feature. Thank you, Niels.
